protected/models/Todo.php
<?php

/**
 * This is the model class for table "account".
 *
 * The followings are the available columns in table 'account':
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $dueOn
 * @property string $createdOn
 * @property string $completed
 * @property string $completedOn
 *
 */
class Todo extends CActiveRecord
{	
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{todo}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, description, dueOn', 'required'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, title, description, dueOn, completedOn, createdOn, completed', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
			'description' => 'Description',
			'dueOn' => 'Due on',
			'createdOn' => 'Created on',
			'completedOn' => 'Completed on',
			'completed' => 'Completed',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('dueOn',$this->dueOn,true);
		$criteria->compare('createdOn',$this->createdOn,true);
		$criteria->compare('completedOn',$this->completedOn,true);
		$criteria->compare('completed',$this->completed,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/TodoController.php
<?php

class TodoController extends Controller
{
    public function actionIndex(){
        $todo = new CActiveDataProvider('Todo',array(
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));
        $this->render('index', array(
            'todo' => $todo
        ));
    }

    public function actionCreate(){
        $model = new Todo();
        if(isset($_POST['Todo'])){
                $model->attributes = $_POST['Todo'];
                if($model->save()){
                        $this->redirect(array('/todo/index'));
                    }
            }
        $this->render('create',['model'=>$model]);
    }
    public function actionSetComplete($ids){
            $pkIds = explode(",", $ids);
            foreach($pkIds as $id){
                    $task = Todo::model()->findByPk($id);
                    $task->completed = 1;
                    $task->completedOn = date("Y-m-d");
                    $task->update();
            }
    }
    public function actionDelete($ids){
            $pkIds = explode(",", $ids);
            foreach($pkIds as $id){
                    $task = Todo::model()->findByPk($id);
                    $task->delete();
            }
    }
}

protected/views/todo/create.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>
<div class="form">
        <?php $form=$this->beginWidget('CActiveForm', array(
            'id'=>'todo-form',
            'enableClientValidation'=>false,
            'clientOptions'=>array(
                'validateOnSubmit'=>true,
            ),
        )); ?>

        <p class="note">Fields with <span class="required">*</span> are required.</p>

        <?php echo $form->errorSummary($model); ?>

        <div class="row">
            <?php echo $form->labelEx($model,'title'); ?>
            <?php echo $form->textField($model,'title'); ?>
            <?php echo $form->error($model,'title'); ?>
        </div>

      <div class="row">
          <?php echo $form->labelEx($model,'description'); ?>
          <?php echo $form->textField($model,'description'); ?>
          <?php echo $form->error($model,'description'); ?>
      </div>

      <div class="row">
          <?php echo $form->labelEx($model,'dueOn'); ?>
          <?php echo $form->dateField($model,'dueOn'); ?>
          <?php echo $form->error($model,'dueOn'); ?>
      </div>


        <div class="row buttons">
            <?php echo CHtml::submitButton('Submit'); ?>
        </div>

        <?php $this->endWidget(); ?>
  </div>

protected/views/todo/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<h1>Todo</h1>
<p><a href="<?php echo $this->createUrl('/todo/create');?>">Create New tasks</a></p>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'all-my-tasks-grid',
	'dataProvider'=>$todo,
	'summaryText' => '<button id="mark-complete">Mark Completed</button>&nbsp;<button id="delete-tasks">Delete Tasks</button>&nbsp;',
	'selectableRows'=>0,
	'columns'=>array(
		array(
			'id'=>'id',
			'class'=>'CCheckBoxColumn',
			'selectableRows' => '50',
		),
		array(
			'name' => 'title',
			'htmlOptions'=> array('align'=>'center'),
		),
		array(
			'name' => 'description',

		),
		array(
			'name' => 'Due Date',
			'value' => '$data->dueOn'
		),
		array(
			'name' => 'Completed',
			'value' => '$data->completed ? "true" : "false"'
		),


	),
)); ?>

<?php

Yii::app()->clientScript->registerScript('js',"
	$(document).ready(function(){
		$('#mark-complete').on('click',function(){
			console.log('test');
				var val = [];
				$('input[name=\"id[]\"]:checked:enabled').each(function(i){
						val[i] = $(this).val();
				});
				if(val.length == 0){
						alert('Please select at least one record!');
						return false;
				}else {
						var c = confirm('Are you sure you want set these as completed.');
						if( c ){
								var ids  = 'ids/'+val.join(',');
								$.get('".Yii::app()->createUrl("todo/setcomplete")."/'+ids)
										.done(function(){
											location.reload()
												/* $.fn.yiiGridView.update('all-my-tasks-grid', {
														data: $(this).serialize()
												}); */
										});
						}
				}
				return false;
		});
	
		$('#delete-tasks').on('click',function(){
			var val = [];
			$('input[name=\"id[]\"]:checked:enabled').each(function(i){
					val[i] = $(this).val();
			});
			if(val.length == 0){
					alert('Please select at least one record!');
					return false;
			}else {
					var c = confirm('Are you sure you want delete these');
					if( c ){
							var ids  = 'ids/'+val.join(',');
							$.get('".Yii::app()->createUrl("todo/delete")."/'+ids)
									.done(function(){
										location.reload()
											/* $.fn.yiiGridView.update('all-my-tasks-grid', {
													data: $(this).serialize()
											}); */
									});
					}
			}
			return false;
		});
	});
	
	
");

?>