protected/models/Users.php
<?php

/**
 * This is the model class for table "account".
 *
 * The followings are the available columns in table 'account':
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $salt
 *
 */
class Users extends CActiveRecord
{	
	public $username;
	public $password;
	public $confirm_password;
	public $rememberMe;
	public $current_password;
	public $new_password;

	private $_identity;
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{users}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username', 'required'),
            array('username', 'unique'),
			array('username, password', 'length', 'max'=>120),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, username, password', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username',
			'password' => 'Password',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('password',$this->password,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function validatePassword($password)
	{
		return true;
		return $this->hashPassword($password,$this->username) === $this->password;
	}
	
	public function hashPassword($password,$username,$salt = '')
	{
		return sha1($username.$password);
	}

	public function autoLogin()
	{
		if (!Yii::app()->user->isGuest)
			return true;

		$model = new LoginForm;
		$model->username = $this->username;

		if ($model->login(true))
			return true;

		return false;
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	
    public function actionIndex(){
        $users = new CActiveDataProvider('Users',array(
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));
        $this->render('index', array(
            'users' => $users
        ));
    }

    public function actionCreate(){
        $model = new Users();
        if(isset($_POST['Users'])){
            $model->username = $_POST['Users']['username'];
            $model->password = $model->hashPassword($_POST['Users']['username'], $_POST['Users']['password']);
                if($model->save()){
                        $this->redirect(array('/user/index'));
                    }
            }
        $this->render('create',['model'=>$model]);
    }
    public function actionDelete($ids){
            $pkIds = explode(",", $ids);
            foreach($pkIds as $id){
                    $task = Users::model()->findByPk($id);
                    $task->delete();
            }
    }
}

protected/views/user/create.php
<?php

$this->pageTitle=Yii::app()->name;
?>
<div class="form">
        <?php $form=$this->beginWidget('CActiveForm', array(
            'id'=>'user-form',
            'enableClientValidation'=>false,
            'clientOptions'=>array(
                'validateOnSubmit'=>true,
            ),
        )); ?>

        <p class="note">Fields with <span class="required">*</span> are required.</p>

        <?php echo $form->errorSummary($model); ?>

        <div class="row">
            <?php echo $form->labelEx($model,'username'); ?>
            <?php echo $form->textField($model,'username'); ?>
            <?php echo $form->error($model,'username'); ?>
        </div>

      <div class="row">
          <?php echo $form->labelEx($model,'password'); ?>
          <?php echo $form->passwordField($model,'password'); ?>
          <?php echo $form->error($model,'password'); ?>
      </div>


        <div class="row buttons">
            <?php echo CHtml::submitButton('Submit'); ?>
        </div>

        <?php $this->endWidget(); ?>
  </div>

protected/views/user/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<h1>Users</h1>
<p><a href="<?php echo $this->createUrl('/user/create');?>">Create New user</a></p>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'all-user-grid',
	'dataProvider'=>$users,
	'summaryText' => '<button id="delete-users">Delete User</button>&nbsp;',
	'selectableRows'=>0,
	'columns'=>array(
		array(
			'id'=>'id',
			'class'=>'CCheckBoxColumn',
			'selectableRows' => '50',
		),
		array(
			'name' => 'username',
			'htmlOptions'=> array('align'=>'center'),
		),


	),
)); ?>

<?php

Yii::app()->clientScript->registerScript('js',"
	$(document).ready(function(){
	
		$('#delete-users').on('click',function(){
			var val = [];
			$('input[name=\"id[]\"]:checked:enabled').each(function(i){
					val[i] = $(this).val();
			});
			if(val.length == 0){
					alert('Please select at least one record!');
					return false;
			}else {
					var c = confirm('Are you sure you want delete these');
					if( c ){
							var ids  = 'ids/'+val.join(',');
							$.get('".Yii::app()->createUrl("user/delete")."/'+ids)
									.done(function(){
										location.reload()
											/* $.fn.yiiGridView.update('all-my-tasks-grid', {
													data: $(this).serialize()
											}); */
									});
					}
			}
			return false;
		});
	});
	
	
");

?>